#
# 20.03.2019 o.javakhishvili@fz-juelich.de
#
EPICS_PV:
  IN_BEAM_Y: EXP:JEDI:WASA:InBeamPos:Y
  GET_BEAM_Y: EXP:JEDI:WASA:GetPos:Y
  DELTA_Y: EXP:JEDI:WASA:DeltaPos:Y
  HOME_Y: EXP:JEDI:WASA:HOME:Y
  STATUS_Y: EXP:JEDI:WASA:Status:Y
  MODE: EXP:JEDI:WASA:MODE
  GUI: EXP:JEDI:WASA:GUI
  COMMAND: EXP:JEDI:WASA:COMMAND
  INSTANCE: EXP:JEDI:WASA:INSTANCE
#
#  distances are in mm
#
VERT_INBEAM_DEFOULT_VALUE: 150

VERT_DELTA_DEFOULT_VALUE: 30

VERT_HOME_DEFOULT_VALUE: 100
