# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WASA_target_control.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 780)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(550, 780))
        MainWindow.setMaximumSize(QtCore.QSize(700, 780))
        MainWindow.setMouseTracking(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.on_off_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.on_off_BTN.setGeometry(QtCore.QRect(30, 28, 120, 48))
        self.on_off_BTN.setAutoDefault(False)
        self.on_off_BTN.setDefault(False)
        self.on_off_BTN.setFlat(False)
        self.on_off_BTN.setObjectName("on_off_BTN")
        self.auto_manual_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.auto_manual_checkbox.setGeometry(QtCore.QRect(160, 30, 91, 40))
        self.auto_manual_checkbox.setObjectName("auto_manual_checkbox")
        self.GROUP_VERTICAL = QtWidgets.QGroupBox(self.centralwidget)
        self.GROUP_VERTICAL.setEnabled(True)
        self.GROUP_VERTICAL.setGeometry(QtCore.QRect(3, 130, 690, 331))
        self.GROUP_VERTICAL.setAutoFillBackground(False)
        self.GROUP_VERTICAL.setFlat(True)
        self.GROUP_VERTICAL.setCheckable(False)
        self.GROUP_VERTICAL.setObjectName("GROUP_VERTICAL")
        self.VERTICAL_HOME_SET_BUTTON = QtWidgets.QPushButton(self.GROUP_VERTICAL)
        self.VERTICAL_HOME_SET_BUTTON.setEnabled(True)
        self.VERTICAL_HOME_SET_BUTTON.setGeometry(QtCore.QRect(600, 235, 60, 60))
        self.VERTICAL_HOME_SET_BUTTON.setObjectName("VERTICAL_HOME_SET_BUTTON")
        self.VERTICAL_DELTA_SET_BUTTON = QtWidgets.QPushButton(self.GROUP_VERTICAL)
        self.VERTICAL_DELTA_SET_BUTTON.setEnabled(True)
        self.VERTICAL_DELTA_SET_BUTTON.setGeometry(QtCore.QRect(600, 155, 60, 60))
        self.VERTICAL_DELTA_SET_BUTTON.setObjectName("VERTICAL_DELTA_SET_BUTTON")
        self.VERTICAL_IN_BEAM_SET_BUTTON = QtWidgets.QPushButton(self.GROUP_VERTICAL)
        self.VERTICAL_IN_BEAM_SET_BUTTON.setEnabled(True)
        self.VERTICAL_IN_BEAM_SET_BUTTON.setGeometry(QtCore.QRect(599, 75, 60, 60))
        self.VERTICAL_IN_BEAM_SET_BUTTON.setObjectName("VERTICAL_IN_BEAM_SET_BUTTON")
        self.VERTICAL_IN_BEAM_TEXT_IN = QtWidgets.QLineEdit(self.GROUP_VERTICAL)
        self.VERTICAL_IN_BEAM_TEXT_IN.setEnabled(True)
        self.VERTICAL_IN_BEAM_TEXT_IN.setGeometry(QtCore.QRect(450, 75, 120, 60))
        self.VERTICAL_IN_BEAM_TEXT_IN.setAccessibleName("")
        self.VERTICAL_IN_BEAM_TEXT_IN.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhSensitiveData)
        self.VERTICAL_IN_BEAM_TEXT_IN.setFrame(True)
        self.VERTICAL_IN_BEAM_TEXT_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.VERTICAL_IN_BEAM_TEXT_IN.setClearButtonEnabled(False)
        self.VERTICAL_IN_BEAM_TEXT_IN.setObjectName("VERTICAL_IN_BEAM_TEXT_IN")
        self.VERTICAL_DELTA_TEXT_IN = QtWidgets.QLineEdit(self.GROUP_VERTICAL)
        self.VERTICAL_DELTA_TEXT_IN.setEnabled(True)
        self.VERTICAL_DELTA_TEXT_IN.setGeometry(QtCore.QRect(450, 155, 120, 60))
        self.VERTICAL_DELTA_TEXT_IN.setAccessibleName("")
        self.VERTICAL_DELTA_TEXT_IN.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhSensitiveData)
        self.VERTICAL_DELTA_TEXT_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.VERTICAL_DELTA_TEXT_IN.setObjectName("VERTICAL_DELTA_TEXT_IN")
        self.VERTICAL_HOME_TEXT_IN = QtWidgets.QLineEdit(self.GROUP_VERTICAL)
        self.VERTICAL_HOME_TEXT_IN.setEnabled(True)
        self.VERTICAL_HOME_TEXT_IN.setGeometry(QtCore.QRect(450, 235, 120, 60))
        self.VERTICAL_HOME_TEXT_IN.setAccessibleName("")
        self.VERTICAL_HOME_TEXT_IN.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhSensitiveData)
        self.VERTICAL_HOME_TEXT_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.VERTICAL_HOME_TEXT_IN.setObjectName("VERTICAL_HOME_TEXT_IN")
        self.IN_BEAM_TEXT_3 = QtWidgets.QLabel(self.GROUP_VERTICAL)
        self.IN_BEAM_TEXT_3.setEnabled(True)
        self.IN_BEAM_TEXT_3.setGeometry(QtCore.QRect(320, 85, 129, 34))
        self.IN_BEAM_TEXT_3.setObjectName("IN_BEAM_TEXT_3")
        self.DELTA_POS_3 = QtWidgets.QLabel(self.GROUP_VERTICAL)
        self.DELTA_POS_3.setEnabled(True)
        self.DELTA_POS_3.setGeometry(QtCore.QRect(320, 165, 121, 34))
        self.DELTA_POS_3.setObjectName("DELTA_POS_3")
        self.HOME_TEXT_3 = QtWidgets.QLabel(self.GROUP_VERTICAL)
        self.HOME_TEXT_3.setEnabled(True)
        self.HOME_TEXT_3.setGeometry(QtCore.QRect(320, 248, 129, 34))
        self.HOME_TEXT_3.setObjectName("HOME_TEXT_3")
        self.MOVE_Y_HOME = QtWidgets.QPushButton(self.GROUP_VERTICAL)
        self.MOVE_Y_HOME.setEnabled(True)
        self.MOVE_Y_HOME.setGeometry(QtCore.QRect(30, 235, 141, 60))
        self.MOVE_Y_HOME.setObjectName("MOVE_Y_HOME")
        self.MOVE_Y_INBEAM = QtWidgets.QPushButton(self.GROUP_VERTICAL)
        self.MOVE_Y_INBEAM.setEnabled(True)
        self.MOVE_Y_INBEAM.setGeometry(QtCore.QRect(30, 75, 141, 60))
        self.MOVE_Y_INBEAM.setObjectName("MOVE_Y_INBEAM")
        self.MOVE_Y_OUTBEAM = QtWidgets.QPushButton(self.GROUP_VERTICAL)
        self.MOVE_Y_OUTBEAM.setEnabled(True)
        self.MOVE_Y_OUTBEAM.setGeometry(QtCore.QRect(30, 155, 141, 60))
        self.MOVE_Y_OUTBEAM.setObjectName("MOVE_Y_OUTBEAM")
        self.label_2 = QtWidgets.QLabel(self.GROUP_VERTICAL)
        self.label_2.setGeometry(QtCore.QRect(450, 0, 211, 17))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(3, 480, 690, 281))
        self.textBrowser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser.setLineWidth(2)
        self.textBrowser.setMidLineWidth(0)
        self.textBrowser.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textBrowser.setOpenLinks(False)
        self.textBrowser.setObjectName("textBrowser")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(570, 40, 86, 25))
        self.comboBox.setMaximumSize(QtCore.QSize(550, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 40, 171, 20))
        self.label.setMaximumSize(QtCore.QSize(550, 16777215))
        self.label.setObjectName("label")
        self.GROUP_VERTICAL.raise_()
        self.on_off_BTN.raise_()
        self.auto_manual_checkbox.raise_()
        self.textBrowser.raise_()
        self.comboBox.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WASA Target Controll"))
        self.on_off_BTN.setText(_translate("MainWindow", "OFF"))
        self.auto_manual_checkbox.setText(_translate("MainWindow", "MANUAL"))
        self.GROUP_VERTICAL.setTitle(_translate("MainWindow", "VERTICAL"))
        self.VERTICAL_HOME_SET_BUTTON.setText(_translate("MainWindow", "SET"))
        self.VERTICAL_DELTA_SET_BUTTON.setText(_translate("MainWindow", "SET"))
        self.VERTICAL_IN_BEAM_SET_BUTTON.setText(_translate("MainWindow", "SET"))
        self.IN_BEAM_TEXT_3.setText(_translate("MainWindow", "IN BEAM  [mm]"))
        self.DELTA_POS_3.setText(_translate("MainWindow", "DELTA POS  [mm]"))
        self.HOME_TEXT_3.setText(_translate("MainWindow", "HOME  [mm]"))
        self.MOVE_Y_HOME.setText(_translate("MainWindow", "Move Y In Home"))
        self.MOVE_Y_INBEAM.setText(_translate("MainWindow", "Move Y IN Beam"))
        self.MOVE_Y_OUTBEAM.setText(_translate("MainWindow", "Move Y Out Beam"))
        self.label_2.setText(_translate("MainWindow", "Min pos - 0; max pos - 152.5mm"))
        self.comboBox.setItemText(0, _translate("MainWindow", "File"))
        self.comboBox.setItemText(1, _translate("MainWindow", "EPICS"))
        self.label.setText(_translate("MainWindow", "Load configuration from:"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
